apiVersion: v1
kind: Pod
metadata:
  name: envvar-demo2
  labels:
    purpose: demonstrate-envvars
  annotations:  
      description: "this pod is created to demonstrate pod annotations"
      jenkins: "https://jenkins.com/build/job/roboshop-catalogue-3"

spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    env: 
    - name: COURSE
      value: "KUBERNETES"
    - name: TRAINER
      value: "siva"