apiVersion: v1
kind: Pod
metadata:
  name: resources
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    resources:
      requests:        # soft limits (guaranteed minimum)
        memory: "64Mi"
        cpu: "100m"
      limits:          # hard limits (maximum allowed)
        memory: "128Mi"
        cpu: "150m"
